import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function GalleryLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-color-bg text-white font-exo'>
        <div className='container mx-auto px-4 py-4'>{children}</div>
      </body>
    </html>
  );
}
